INSERT INTO smn_cont_costos.smn_bases_distribucion
(
	smn_bases_distribucion_id,
	bdi_codigo,
	bdi_descripcion,
	bdi_forma_calculo,
	smn_nivel_distribucion_id,
	bdi_tipo_distribucion,
	smn_cuenta_mayor_rf,
	smn_modelo_comprobante_rf,
	smn_criterio_distribucion_id,
	bdi_estatus,
	bdi_idioma,
	bdi_usuario,
	bdi_fecha_registro,
	bdi_hora
)
VALUES
(
	${seq:currval@smn_cont_costos.seq_smn_bases_distribucion},
	${fld:bdi_codigo},
	${fld:bdi_descripcion},
	${fld:bdi_forma_calculo},
	${fld:smn_nivel_distribucion_id},
	${fld:bdi_tipo_distribucion},
	${fld:smn_cuenta_mayor_rf},
	${fld:smn_modelo_comprobante_rf},
	${fld:smn_criterio_distribucion_id},
	${fld:bdi_estatus},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
)
