select
	smn_cont_costos.smn_elemento.smn_elemento_id,
	smn_cont_costos.smn_elemento.ele_codigo as ele_codigo_pl0,
select
select
	smn_cont_costos.smn_rel_servicio_elemento.smn_servicios_rf,
	smn_cont_costos.smn_rel_servicio_elemento.smn_elemento_id,
	smn_cont_costos.smn_rel_servicio_elemento.rse_idioma,
	smn_cont_costos.smn_rel_servicio_elemento.rse_usuario,
	smn_cont_costos.smn_rel_servicio_elemento.rse_fecha_registro,
	smn_cont_costos.smn_rel_servicio_elemento.rse_hora,
		smn_cont_costos.smn_rel_servicio_elemento.smn_rel_servicio_elemento_id
from
	smn_cont_costos.smn_elemento,
	smn_cont_costos.smn_rel_servicio_elemento
where
	smn_cont_costos.smn_elemento.smn_elemento_id=smn_cont_costos.smn_rel_servicio_elemento.smn_elemento_id
	and
	smn_rel_servicio_elemento_id = ${fld:id}
